#!/usr/bin/env bash

# -- Prepend ---------------------------------------------------------------------------------------
declare -a prepend_dirs=(
    "/usr/local/bin"
)

if [ -n "$ZSH_VERSION" ]; then
    for index in $prepend_dirs
    do
        PATH="$index:$PATH"
    done
else
    for index in ${!prepend_dirs[*]}
    do
        if [ -d ${prepend_dirs[$index]} ]; then
            PATH="${prepend_dirs[$index]}:$PATH"
        fi
    done
fi

unset prepend_dirs

# -- Append ----------------------------------------------------------------------------------------
declare -a append_dirs=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/dotfiles/bin"
    "$HOME/n/bin"
)

if [ -n "$ZSH_VERSION" ]; then
    for index in $append_dirs
    do
        PATH="$index:$PATH"
    done
else
    for index in ${!append_dirs[*]}
    do
        if [ -d ${append_dirs[$index]} ]; then
            PATH="${append_dirs[$index]}:$PATH"
        fi
    done
fi

unset append_dirs

# -- Export ------------------------------------------------------------------------------
export PATH
