#!/usr/bin/env bash

# -- Load .bashrc ----------------------------------------------------------------------------------
for file in ~/.{bash_aliases,bash_exports,bash_functions,bash_nocommit,bash_options,bash_path}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done

unset file

# -- Message ---------------------------------------------------------------------------------------
shopt -q login_shell && command -v screenfetch >/dev/null 2>&1 && {
    echo "$(screenfetch)"
}
