#!/usr/bin/env bash

# -- Load .bashrc ----------------------------------------------------------------------------------
for file in ~/.{bash_aliases,bash_exports,bash_functions,bash_nocommit,bash_options,bash_paths}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done

unset file

# -- Message ---------------------------------------------------------------------------------------
[[ -o login ]] || shopt -q login_shell 2>/dev/null && command -v screenfetch >/dev/null 2>&1 && {
    echo "$(screenfetch)"
}
