#!/usr/bin/env bash

function run_help() {
    cat <<EOF
Dotfiles - Stephen Ribich <stephen.ribich@gmail.com>

Usage: $(basename "$0") [options]

Options:
    -h, --help          Print this help text
        --defaults      Install all defaults without any prompts
        --no-packages   Suppress package updates
        --no-sync       Suppress repository syncing

Documentation can be found at https://github.com/nulliel/dotfiles/

Copyright (c) Stephen Ribich
Licenced under the MIT license.
EOF
}
