#!/usr/bin/env bash

function run_help() {
    cat <<EOF
Usage: $(basename "$0") [options]

Options:
        --defaults      Install all defaults without any prompts
    -h, --help          Print this help text
        --no-packages   Suppress package updates
        --no-sync       Suppress repository syncing

Documentation can be found at https://github.com/nulliel/dotfiles/
EOF
}
