#!/usr/bin/env bash

u_header "package"
u_print "Installing packages..."

if [[ $NO_PACKAGES ]]; then
    u_skip
    return
fi

new_line

source $DOTFILES_DIRECTORY/package/chrome

source $DOTFILES_DIRECTORY/package/qbittorrent

source $DOTFILES_DIRECTORY/package/deadbeef

u_exit_header
