#!/usr/bin/env bash

header "package"

#-- Check for flags --------------------------------------------------------------------------------
if is_set "NO_PACKAGES"; then
  skip "Installing packages..."
  exit_header && return
fi

logl "Installing packages..."

#-- Utilities --------------------------------------------------------------------------------------
function load_package() {
  sleep 0.05
  source "${DOTFILES_DIR}/packages/$1"
}

#-- Packages ---------------------------------------------------------------------------------------

# Browsers
load_package "chrome"

# Editors
#load_package "emacs"

# Scripts
#load_package "nvm"

# Social
load_package "skype"
load_package "slack"

# Utility
#load_package "qbittorrent"  # A torrent client
#load_package "deadbeef"     # An audio player
#load_package "mpv"          # A video player

exit_header
