#!/usr/bin/env bash

u_header "sync"

#-- Confirm Sync -----------------------------------------------------------------------------------
if [[ "$NO_SYNC" = false && "$INSTALL_DEFAULTS" = false ]]; then
  seek_confirmation "Sync dotfiles?"
elif [[ "$NO_SYNC" = false && "$INSTALL_DEFAULTS" = true ]]; then
  set_confirmed
fi

if is_confirmed; then
  #-- Initialize the git repository ----------------------------------------------------------------
  u_print "Initializing git repository..."

  if [[ "$(git rev-parse --is-inside-work-tree 1>/dev/null 2>&1)" = "false" ]]; then
    git init || { u_fail; exit 1; }
    git remote add origin "${DOTFILES_GIT_REMOTE}" || { u_fail; exit 1; }

    u_pass
  else
    u_skip
  fi

  #-- Sync the repository --------------------------------------------------------------------------
  u_print "Syncing dotfiles..."
  show_progress git pull --rebase origin master || {
    u_fail
    exit 1
  }
  u_pass

  #-- Update modules -------------------------------------------------------------------------------
  u_print "Updating submodules..."
  show_progress git submodule update --recursive --init || {
    u_fail
    exit 1
  }
  u_pass
else
  u_print "Syncing dotfiles..."
  u_skip
fi

u_exit_header
