#!/usr/bin/env bash

header "sync"

#-- Check flags ------------------------------------------------------------------------------------
if is_set "NO_SYNC"; then
  skip "Syncing dotfiles..."
  exit_header && return
fi

#-- Confirm Sync -----------------------------------------------------------------------------------
if ! confirm_default "Sync dotfiles?"; then
  skip "Syncing dotfiles..."
  exit_header && return
fi

#-- Initialize the git repository ------------------------------------------------------------------
log "Initializing git repository..."

if [[ "$(git rev-parse --is-inside-work-tree 1>/dev/null 2>&1)" = "false" ]]; then
  git init || {
    fail
    die "Failed to initialize git repository" 21
  }

  git remote add origin "${DOTFILES_GIT_REMOTE}" || {
    fail
    die "Failed to add remote" 22
  }

  pass
else
  skip
fi

#-- Sync the repository ----------------------------------------------------------------------------
log "Syncing dotfiles..."
show_progress git pull --rebase origin master || {
  fail
  die "Failed to sync to remote repository" 23
}

pass

#-- Update modules ---------------------------------------------------------------------------------
log "Updating submodules..."
show_progress git submodule update --recursive --init || {
  fail
  die "Failed to update submodules" 24
}

pass

exit_header
