#!/usr/bin/env bash

u_header "sync"

#-- Check flags ------------------------------------------------------------------------------------
if [[ "$NO_SYNC" = true ]]; then
  u_skip "Syncing dotfiles..."
  u_exit_header && return
fi

#-- Confirm Sync -----------------------------------------------------------------------------------
if ! poll_confirm "Sync dotfiles?" true; then
  u_skip "Syncing dotfiles..."
  u_exit_header && return
fi

#-- Initialize the git repository ------------------------------------------------------------------
u_print "Initializing git repository..."

if [[ "$(git rev-parse --is-inside-work-tree 1>/dev/null 2>&1)" = "false" ]]; then
  git init || do_fail
  git remote add origin "${DOTFILES_GIT_REMOTE}" || do_fail

  u_pass
else
  u_skip
fi

#-- Sync the repository ----------------------------------------------------------------------------
u_print "Syncing dotfiles..."
u_return show_progress git pull --rebase origin master

#-- Update modules ---------------------------------------------------------------------------------
u_print "Updating submodules..."
u_return show_progress git submodule update --recursive --init

u_exit_header
