#!/usr/bin/env bash

#-- Config -----------------------------------------------------------------------------------------
local rpmfusion_free="https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
local rpmfusion_nonfree="https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

#-- Repository information -------------------------------------------------------------------------
declare _RPMFUSION_REPO_ACTIVATED=false

#-- Enable repositories ----------------------------------------------------------------------------
enable_repository () {
  case "$1" in
    "rpmfusion")
      subheader "rpmfusion"

      package_install "$rpmfusion_free"
      package_install "$rpmfusion_nonfree"

      _RPMFUSION_REPO_ACTIVATED=true

      exit_subheader
      ;;
    "*")
      error "Repository $1 does not exist"
      exit 1
      ;;
  esac
}

#-- Check repositories -----------------------------------------------------------------------------
repository_activated () {
  case "$1" in
    "rpmfusion")
      if [[ "$_RPMFUSION_REPO_ACTIVATED" = true ]]; then
        return 0
      fi

      return 1
      ;;
    "*")
      error "Repository $1 does not exist"
      exit 1
      ;;
    esac
}
