#!/usr/bin/env bash

#-- Check for existing package ---------------------------------------------------------------------
package_installed () {
  dnf list installed "$1" >/dev/null 2>&1 \
    || command_exists "$1" \
    || return 1

  return 0
}

#-- Package install --------------------------------------------------------------------------------
package_install () {
  log "Installing $1..."

  if package_installed "$1"; then
    skip && return
  fi

  show_progress sudo dnf install -y "$1" && pass || {
    fail
    die "Package ($1) failed to install" 41
  }
}
package_groupinstall () {
  log "Installing $1..."

  show_progress sudo dnf groupinstall -y "'$@'" && pass || {
      fail
      die "Group ($1) failed to install" 42
    }
}

#-- Build tools ------------------------------------------------------------------------------------
install_build_tools () {
  package_groupinstall "Development Tools"
  package_groupinstall "C Development Tools and Libraries"

  package_install "autoconf"
  package_install "automake"
}
