#!/usr/bin/env bash

#-- Utilities --------------------------------------------------------------------------------------
# $1 - Download source
# $2 - Folder to extract to
_do_build_download () {
  log "Downloading tarball..."

  if [[ -f "$2" ]]; then
    rm "$2"
  fi

  wget "$1" -q -O "$2" || {
    fail
    die "Failed to download archive $1" 31
  }

  pass
}

# $1 - File to extract
# $2 - Folder to extract to
_do_build_extract () {
  log "Extracting tarball..."

  if [[ -d "$2" ]]; then
    rm -r "$2"
  fi

  mkdir "$2"

  tar -zxf "$1" -C "$2" --strip-components=1 || {
    fail
    die "Failed to extract archive $1" 32
  }

  pass
}

# $1 - Build system (make, waf)
_do_build_autogen () {
  case "$1" in
    "make")
      log "Running ./autogen.sh..."

      if [[ ! -f "./autogen.sh" ]]; then
        skip && return
      fi

      show_progress ./autogen.sh || {
        fail
        die "Build failed on ./autogen.sh" 51
      }

      pass
      ;;
    "waf")

      ;;
    *)
      error "Unknown build tool $1" && exit 1
      ;;
  esac
}

# $1 - Build system (make, waf)
# $@ - Arguments
_do_build_configure () {
  local build_system="$1"
  shift

  case "$build_system" in
    "make")
      log "Running ./configure $@..."

      if [[ ! -f "./configure" ]]; then
        skip && return
      fi

      show_progress ./configure "$@" || {
        fail
        die "Build failed on ./configure $@" 52
      }

      pass
      ;;
    "waf")

      ;;
    *)
      error "Unknown build tool $1" && exit 1
      ;;
  esac
}

# $1 - Build system (make, waf)
_do_build_make () {
  case "$1" in
    "make")
      log "Running make..."

      show_progress make || {
        fail
        die "Build failed on make" 53
      }

      pass
      ;;
    "waf")

      ;;
    *)
      error "Unknown build tool $1" && exit 1
      ;;
  esac
}

# $1 - Build system (make, waf)
_do_build_install () {
  case "$1" in
    "make")
      log "Running make install.."

      show_progress sudo make install || {
        fail
        die "Build failed on make install" 54
      }

      pass
      ;;
    "waf")

      ;;
    *)
      error "Unknown build tool $1" && exit 1
      ;;
  esac
}

# $1 - Tarball to delete
# $2 - Extracted folder to delete
_do_build_cleanup () {
  log "Cleaning up..."

  if [[ -f "$1" ]]; then
    rm "$1"
  fi

  if [[ -d "$2" ]]; then
    rm -r "$2"
  fi

  pass
}

#-- WAF build sytem --------------------------------------------------------------------------------
do_waf_install () {
  :
}

#-- Make build system ------------------------------------------------------------------------------
# $1 - Download source
# $@ - Configure arguments
do_make_install () {
  local source_url="$1"                                             # URL to download
  local source_file="${DOTFILES_TMP}/$(random_string 16).tar.gz"    # File to download to
  local source_folder="${DOTFILES_TMP}/$(random_string 16)"         # Folder to extract to

  shift

  _do_build_download "$source_url" "$source_file"
  _do_build_extract "$source_file" "$source_folder"

  cd "$source_folder"

  _do_build_autogen "make"
  _do_build_configure "make" "$@"
  _do_build_make "make"
  _do_build_install "make"

  _do_build_cleanup "$source_file" "$source_folder"
}
