#!/usr/bin/env bash

if [[ "${noSync}" == true ]]; then
    console.skip "Syncing dotfiles..."
    return
fi

#-- Initialize the git repository ------------------------------------------------------------------
console.raw "Initializing git repository..."

if ! git rev-parse --is-inside-work-tree 1>/dev/null 2>&1; then
    if ! git init 1>/dev/null 2>&1; then
        console.fail && exit 1
    fi

    if ! git remote add origin "${DOTFILES_REMOTE}" 1>/dev/null 2>&1; then
        console.fail && exit 1
    fi

    if ! git fetch origin master 1>/dev/null 2>&1; then
        console.fail && exit 1
    fi

    if ! git reset --hard FETCH_HEAD 1>/dev/null 2>&1; then
        console.fail && exit 1
    fi

    git clean -fd 1>/dev/null 2>&1

    console.pass
else
    console.skip
fi

#-- Sync the repository ----------------------------------------------------------------------------
console.raw "Syncing dotfiles..."

if ! git pull --rebase origin master 1>/dev/null 2>&1; then
    console.fail && exit 1
fi

console.pass
