#!/usr/bin/env bash

#-- Definitions ---------------------------------------------------------------------
packageInstall () {
  local packageName="${1}"
  local noconfirm=false

  if [[ "${packageName:0:11}" == "--noconfirm" ]]; then
    packageName="${2}"
    noconfirm=true
  fi

  trySubheader "${packageName}"

  if _packageInstalled "${packageName}"; then
    skip "Installing ${packageName}..."
    tryExitSubheader "${packageName}"
    return
  fi

  clog "Installing ${packageName}..."

  if [[ "${noconfirm}" == true ]]; then
    checkSuccess showProgress sudo pacman -Syu --needed --noconfirm "${packageName}" \
      || fatal "Package (${packageName}) failed to install"
  else
    checkSuccess showProgress sudo pacman -Syu --needed "${packageName}" \
      || fatal "Package (${packageName}) failed to install"
  fi

  tryExitSubheader "${packageName}"
}

packageInstallList () {
  local title="${1}"; shift
  trySubheader "${title}"

  while [[ "${#}" -ne 0 ]]; do
    packageInstall "${1}"
    shift
  done

  tryExitSubheader "${title}"
}

#-- Utilities --------------------------------------------------------------------------------------
_packageInstalled () {
  pacman -Q "$1" >/dev/null 2>&1 \
    || commandExists "$1" \
    || return 1
  return 0
}
