#!/usr/bin/env bash

#-- Check flags ------------------------------------------------------------------------------------
if [[ "$NO_SYNC" = true ]]; then
  skip "Syncing dotfiles..."
  return
fi

#-- Initialize the git repository ------------------------------------------------------------------
clogl "Initializing git repository..."

if [[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]]; then
  git init 1>&3 2>&4 || {
    fail
    fatal "Failed to initialize git repository"
  }

  git remote add origin "${DOTFILES_GIT_REMOTE}" 1>&3 2>&4 || {
    fail
    fatal "Failed to add remote"
  }

  git fetch origin master 1>&3 2>&4 || {
    fail
    fatal "Failed to fetch origin"
  }

  git reset --hard FETCH_HEAD 1>&3 2>&4 || {
    fail
    fatal "Failed to reset branch"
  }

  git clean -fd 1>&3 2>&4

  pass
else
  skip
fi

#-- Sync the repository ----------------------------------------------------------------------------
clogl "Syncing dotfiles..."

git pull --rebase origin master 1>&3 2>&4 || {
  fail
  fatal "Failed to sync to remote repository"
}

pass

#-- Update modules ---------------------------------------------------------------------------------
clogl "Updating submodules..."

git submodule update --recursive --init 1>&3 2>&4 || {
  fail
  fatal "Failed to update submodules"
}

pass
