#!/usr/bin/env bash

#-- Config -----------------------------------------------------------------------------------------
declare -i _headerColors=(91 92 93 94 95 96)

declare _headerValue=""
declare _headerColor=0

declare _subheaderValue=""
declare _subheaderColor=0

declare _headless=false

#-- Definitions ------------------------------------------------------------------------------------
header () {
  _toggleHeader
  _headerValue="${1}"
  return 0
}

exitHeader () {
  _headerValue=""
  return 0
}

tryHeader () {
  [[ "${_headerValue}" == "" ]] && _headerValue="${1}"
  return 0
}

tryExitHeader () {
  [[ "${_headerValue}" == "${1}" ]] && _headerValue=""
  return 0
}

inHeader () {
  [[ "${_headerValue}" == "" ]] && return 1 || return 0;
}

#-- Definitions ------------------------------------------------------------------------------------
subheader () {
  _toggleSubheader
  _subheaderValue="${1}"
  return 0
}

exitSubheader () {
  _subheaderValue=""
  return 0
}

trySubheader () {
  [[ "${_subheaderValue}" == "" ]] && _subheaderValue="${1}"
  return 0
}

tryExitSubheader () {
  [[ "${_subheaderValue}" == "${1}" ]] && _subheaderValue=""
  return 0
}

inSubheader () {
  [[ "${_subheaderValue}" == "" ]] && return 1 || return 0;
}

#-- Utilities --------------------------------------------------------------------------------------
_toggleHeader () {
  _headerColor="$(( $(( _headerColor + 1 )) % ${#_headerColors[@]} ))"
}

_toggleSubheader () {
  _subheaderColor="$(( $(( _subheaderColor + 1 )) % ${#_headerColors[@]}))"
}

_printHeader () {
  local headless_length=0

  if [[ "${_headless}" = true ]]; then
    if [[ "${_subheaderValue}" != "" ]]; then
      headless_length=$(( ${#_subheaderValue} + 5 ))
    elif [[ "${_headerValue}" != "" ]]; then
      headless_length=$(( ${#_headerValue} + 3 ))
    fi

    for _ in $(seq 1 "${headless_length}"); do
      printf " "
    done

    _headless=false
    return
  fi

  if [[ "${_subheaderValue}" != "" ]]; then
    printf "  [\033[1;%bm%b\033[0m] " "${_headerColors[${_subheaderColor}]}" "${_subheaderValue}"
  elif [[ "${_headerValue}" != "" ]]; then
    printf "[\033[1;%bm%b\033[0m] " "${_headerColors[${_headerColor}]}" "${_headerValue}"
  fi
}
