#!/usr/bin/env bash

#-- Config -----------------------------------------------------------------------------------------
export SCRIPT_HEIGHT="$(tput lines)"

#-- Log input to file ------------------------------------------------------------------------------
write_to_log () {
  IFS=''
  while read -r data; do
    printf "%b\n" "$data" \
      | sed -r "s/\r//g" \
      | sed -r "s/\x1B\[\?7[l|h]//g" \
      | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K|A]//g" \
      >>"$DOTFILES_LOG"
  done

  # Hack to maintain a copy of the actual height
  SCRIPT_HEIGHT="$(tput lines)"
}

#-- Redirect output --------------------------------------------------------------------------------
redirect_output () {
  # fd 1 - stdout
  # fd 2 - stderr
  # fd 3 - $DOTFILES_LOG
  # fd 4 - $DOTFILES_LOG
  # fd 5 - stdout + $DOTFILES_LOG
  # fd 6 - stderr + $DOTFILES_LOG
  exec 3> >(write_to_log)      \
       4> >(write_to_log)      \
       5> >(tee /dev/fd/3)     \
       6> >(tee /dev/fd/4 >&2)
}

restore_output() {
  if { true 1>&3; } 2>/dev/null; then
    exec 1>&3 \
         2>&4 \
         3>&- \
         4>&- \
         5>&- \
         6>&-
  fi
}
