#!/usr/bin/env bash

#-- Check for existing package ---------------------------------------------------------------------
package_installed () {
  pacman -Q "$1" >/dev/null 2>&1 \
    || command_exists "$1" \
    || return 1
  return 0
}

#-- Package install --------------------------------------------------------------------------------
package_install () {
  log "Installing $1..."

  if package_installed "$1"; then
    skip && return
  fi

  show_progress sudo pacman -Syu --needed "$1" && pass || {
    fail
    fatal "Package ($1) failed to install"
  }
}

#-- Build tools ------------------------------------------------------------------------------------
install_build_tools () {
  package_install "base-devel"
}
