#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090

#-- Config -----------------------------------------------------------------------------------------
DOTFILES_FD_3=false
DOTFILES_FD_4=false
DOTFILES_FD_5=false
DOTFILES_FD_6=false

#-- Definitions --------------------------------------------------------------------------------
redirectOutput () {
  # fd 3 - $DOTFILES_LOG
  # fd 4 - $DOTFILES_LOG
  eval "exec {FD}> >(_writeLog)" && DOTFILES_FD_3="${FD}"
  eval "exec {FD}> >(_writeLog)" && DOTFILES_FD_4="${FD}"

  # fd 5 - stdout + $DOTFILES_LOG
  # fd 6 - stderr + $DOTFILES_LOG
  eval "exec {FD}> >(tee /dev/fd/${DOTFILES_FD_3} >&1)" && DOTFILES_FD_5="${FD}"
  eval "exec {FD}> >(tee /dev/fd/${DOTFILES_FD_4} >&2)" && DOTFILES_FD_6="${FD}"
}

restoreOutput() {
  for i in $(seq 3 6); do
    local str="DOTFILES_FD_${i}"
    eval "exec ${!str}>&-"
  done
}

#-- Utilities --------------------------------------------------------------------------------------
_writeLog () {
  IFS=''
  while read -r data; do
    printf "%b\n" "$data" \
      | sed -r "s/\r//g" \
      | sed -r "s/\x1B\[\?7[l|h]//g" \
      | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K|A]//g" \
      >>"$DOTFILES_LOG"
  done
}
