#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090

#-- Definitions ------------------------------------------------------------------------------------
randomString () {
  # $1 - Number of bytes to return
  tr -dc "a-zA-Z0-9" </dev/urandom | fold -w "${1:-32}" | head -n 1
}

saveCursor () {
  # $1 - Variable name to save cursor data into
  local oldstty

  exec </dev/tty
  oldstty=$(stty -g)
  stty raw -echo min 0
  printf "\033[6n" >/dev/tty
  IFS=';' read -r -d R -a pos
  stty "$oldstty"
  eval "${1}[0]=$(( ${pos[0]:2} - 1 ))"
  eval "${1}[1]=$(( pos[1] - 1 ))"
}

restoreCursor () {
  # $1 - Variable name to get cursor data out of
  local arr="${1}[@]"
  arr=(${!arr})

  tput cup "${arr[0]}" "${arr[1]}"
}
