#!/usr/bin/env bash

return 1

header "link"

#-- Link function ----------------------------------------------------------------------------------
linkHome () {
  local linkFrom="${DOTFILES_DIR}/links/$1"
  local linkTo="${HOME}/$2"
  local linkPath="$(readlink -f ${linkTo})"

  console "Linking ${linkTo}..."

  if [[ -f "${linkTo}" || -d "${linkTo}" || -f "${linkPath}" ]]; then
    if [[ "${linkPath}" = "${linkFrom}" ]]; then
      skip
      return
    fi

    fail "File ${linkTo} already exists."
  fi

  ln -s "${linkFrom}" "${linkTo}" || {
    fail "Failed to create link ${linkFrom}->${linkTo}"
  }

  pass
}

#-- Links ------------------------------------------------------------------------------------------
linkHome "shell/bash_aliases"   ".bash_aliases"
linkHome "shell/bash_exports"   ".bash_exports"
linkHome "shell/bash_functions" ".bash_functions"
# linkHome "shell/bash_nocommit"  ".bash_nocommit"
linkHome "shell/bash_options"   ".bash_options"
linkHome "shell/bash_paths"     ".bash_paths"
linkHome "shell/bash_profile"   ".bash_profile"
linkHome "shell/bashrc"         ".bashrc"
linkHome "config/deadbeef"      ".config/deadbeef"
linkHome "config/mpv"           ".config/mpv"
# linkHome "emacs.d"              ".emacs.d"
linkHome "git/gitconfig"        ".gitconfig"
linkHome "git/gitignore"        ".gitignore"
# linkHome "config/npmrc"         ".npmrc"

exitHeader
