#!/usr/bin/env bash

return 1







header "package"

#-- Check for flags --------------------------------------------------------------------------------
clog --linefeed "Installing packages..."

#-- Utilities --------------------------------------------------------------------------------------
npmInstall () {
  trySubheader "npm"

  console "Installing npm package ${1}..."
  checkSuccess showProgress "${DOTFILES_USR}/bin/npm" install --global "${1}"

  tryExitSubheader "npm"
}

#-- Core Packages ----------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Core"

packageInstall --noconfirm "wget"
packageInstall --noconfirm "base-devel"

#-- Compression ------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Compression"

packageGit --name "zopfli"                               \
           --repo "https://github.com/google/zopfli.git" \
           --type "make"                                 \
           --post ". ${DOTFILES_DIR}/packages/zopfli-post"

packageInstall "pigz"

#-- Fonts ------------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Fonts"

packageInstallList "font"                           \
                   "adobe-source-code-pro-fonts"    \
                   "adobe-source-han-sans-jp-fonts"

#-- Sound ------------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Sound"

packageInstallList "sound"       \
                   "alsa-lib"    \
                   "pulseaudio"  \
                   "pavucontrol"

#-- Editors ----------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Editors"

packageGit --name "emacs"                                     \
           --repo "https://github.com/emacs-mirror/emacs.git" \
           --type "make"                                      \
           --opts "--with-x-widgets"                          \
           --deps "texinfo"                                   \
                  "libxpm"                                    \
                  "libjpeg-turbo"                             \
                  "libtiff"                                   \
                  "giflib"                                    \
                  "ncurses"                                   \
                  "gtk3"                                      \
                  "webkitgtk"                                 \
                  "m17n-lib"                                  \
                  "imagemagick"

# Emacs Addons
packageInstallList "emacs-other"         \
                   "the_silver_searcher"

#-- Browsers ---------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Browsers"

packageGit --name "google-chrome"                               \
           --repo "https://aur.archlinux.org/google-chrome.git" \
           --type "aur"                                         \
           --deps "alsa-lib"                                    \
                  "gconf"                                       \
                  "gtk2"                                        \
                  "libxss"                                      \
                  "libxtst"                                     \
                  "nss"

#-- Node -------------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Node.js"

packageGit --name "n"                                         \
           --repo "https://github.com/tj/n.git"               \
           --type "none"                                      \
           --post "source ${DOTFILES_DIR}/packages/n-post"

if ! echo "${PATH}" | grep "${DOTFILES_USR}/bin"; then
  export PATH="${PATH}:${DOTFILES_USR}/bin"
fi

N_PREFIX="${DOTFILES_USR}"

npmInstall tern
npmInstall eslint

#-- Utilities --------------------------------------------------------------------------------------
console --noheader --bold --linefeed "\n  Utilities"

packageInstallList "Utilities"   \
                   "qbittorrent" \
                   "deadbeef"    \
                   "mpv"         \
                   "screenfetch"

exitHeader
