#!/usr/bin/env bash

# -- Make emacs the default editor -----------------------------------------------------------------
export EDITOR='emacs -nw -Q'

# -- Node exports ----------------------------------------------------------------------------------
export BABEL_CACHE_PATH="${HOME}/.cache/babel.json"
export N_PREFIX="${HOME}/.dotfiles/.usr"
