#!/usr/bin/env bash

# -- Exit ZSH Shell --------------------------------------------------------------------------------
[[ -n  "$ZSH_VERSION" ]] && return

# -- Options --------------------------------------------------------------------------------------
shopt -s autocd
shopt -s cdspell
shopt -s globstar
