#!/usr/bin/env bash

# -- Create a directory and enter it ---------------------------------------------------------------
function mkd() {
    mkdir -p "$@" && cd "$_"
}

# -- Create a tar.gz archive -----------------------------------------------------------------------
function targz() {
    local tmpFile="${@%/}.tar"

    tar -cvf "${tmpFile}" "${@}" || return 1

    size=$(
        stat -f"%z" "${tmpFile}" 2> /dev/null
        stat -c"%s" "${tmpFile}" 2> /dev/null
    )

    local cmd="";

    if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
        cmd="zopfli"
    else
        if hash pigz 2> /dev/null; then
            cmd="pigz"
        else
            cmd="gzip"
        fi
    fi

    echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…"
    "${cmd}" -v "${tmpFile}" || return 1

    [ -f "${tmpFile}" ] && rm "${tmpFile}"

    zippedSize=$(
        stat -f"%z" "${tmpFile}.gz" 2> /dev/null
        stat -c"%s" "${tmpFile}.gz" 2> /dev/null
    )

    echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully."
}
