#!/usr/bin/env bash

u_subheader "chrome"

if cmd_exists google-chrome; then
    u_print "Google Chrome is already installed..."
    u_skip
    return
fi

if [[ ! $INSTALL_DEFAULTS ]]; then
    seek_confirmation "Install Google Chrome?"
else
    set_confirmed
fi

if ! is_confirmed; then
    u_print "Installing Google Chrome..."
    u_skip
    return
fi

#-- Add google repository --------------------------------------------------------------------------
u_print "Adding google-chrome repository..."

if [[ -f /etc/yum.repos.d/google-chrome.repo ]]; then
    u_pass
else
    REPO_CONTENTS="[google-chrome]
name=google-chrome
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
"

    sudo bash -c "echo \"${REPO_CONTENTS}\" > /etc/yum.repos.d/google-chrome.repo"
    u_pass
fi

#-- Release install --------------------------------------------------------------------------------
if [[ ! $INSTALL_DEFAULTS ]]; then
    u_selection "^Which release would you like to install?" \
                "#2" \
                "beta" \
                "stable" \
                "unstable"
else
    set_selection "stable"
fi

u_print "Installing google-chrome-$SELECTION_VALUE..."

case $SELECTION_VALUE in
    "beta")
        package_install google-chrome-beta && u_pass || u_fail && exit
        ;;
    "stable")
        package_install google-chrome-stable && u_pass || u_fail && exit
        ;;
    "unstable")
        package_install google-chrome-unstable && u_pass || u_fail && exit
        ;;
esac

u_exit_subheader
