#!/usr/bin/env bash

u_subheader "deadbeef"

if cmd_exists deadbeef; then
    u_print "DeaDBeeF is already installed..."
    u_skip
    return
fi

if [[ ! $INSTALL_DEFAULTS ]]; then
    seek_confirmation "Install DeaDBeeF?"
else
    set_confirmed
fi

if ! is_confirmed; then
    u_print "Installing DeaDBeeF..."
    u_skip
    return
fi

#-- Dependencies -----------------------------------------------------------------------------------
install_build_tools

package_install libsamplerate
package_install jansson
package_install jansson-devel
package_install alsa-lib
package_install libvorbis
package_install libogg
package_install imlib2
package_install libjpeg
package_install libpng
package_install flac
package_install flac123
package_install flac-devel
package_install flac-libs
package_install wavpack
package_install libsndfile
package_install libcdio
package_install dbus
package_install pulseaudio
package_install zlib
package_install libzip
package_install yasm

#-- Install ----------------------------------------------------------------------------------------
cd /tmp

# Download tarball
u_print "Downloading DeaDBeeF tarball..."

if [[ ! -f /tmp/0.7.2.tar.gz ]]; then
    run_silent wget https://github.com/Alexey-Yakovenko/deadbeef/archive/0.7.2.tar.gz
    check_success
else
    u_skip
fi

# Extract tarball
u_print "Extracting tarball..."

tar -zxf /tmp/0.7.2.tar.gz
rm  /tmp/0.7.2.tar.gz

u_pass

# Run installation scripts
cd /tmp/deadbeef-0.7.2

u_print "Running ./autogen.sh..."
run_log ./autogen.sh
check_success

u_print "Running ./configure..."
run_log ./configure
check_success

u_print "Running make..."
run_log make
check_success

u_print "Running make install..."
run_log sudo make install
check_success

u_exit_subheader
