#!/usr/bin/env bash

u_subheader "deadbeef"

if cmd_exists deadbeef; then
    u_print "DeaDBeeF is already installed..."
    u_skip
    return
fi

if [[ ! $INSTALL_DEFAULTS ]]; then
    seek_confirmation "Install DeaDBeeF?"
else
    set_confirmed
fi

if ! is_confirmed; then
    u_print "Installing DeaDBeeF..."
    u_skip
    return
fi

#-- Dependencies -----------------------------------------------------------------------------------
install_build_tools

package_install libsamplerate-devel
package_install jansson-devel
package_install alsa-lib-devel
package_install libvorbis-devel
package_install libcurl-devel
package_install libogg-devel
package_install imlib2-devel
package_install libjpeg-turbo-devel
package_install libpng-devel
package_install libmad-devel
package_install mpg123
package_install flac-devel
package_install wavpack-devel
package_install libsndfile-devel
package_install libcdio-devel
package_install ffmpeg-devel
package_install dbus-devel
package_install pulseaudio-libs-devel
package_install faad2-devel
package_install zlib-devel
package_install libzip-devel
package_install yasm-devel
package_install mesa-libGLU-devel
package_install libcddb-devel
package_install libICE-devel
package_install libSM-devel
package_install gstreamer-{ffmpeg,plugins-{good,ugly,bad{,-free,-nonfree}}}
package_install glib-devel
package_install glib2-devel

#-- Install ----------------------------------------------------------------------------------------
cd /tmp

# Download tarball
u_print "Downloading DeaDBeeF tarball..."

if [[ ! -f /tmp/0.7.2.tar.gz ]]; then
    silent_output wget https://github.com/Alexey-Yakovenko/deadbeef/archive/0.7.2.tar.gz
    check_success
else
    u_skip
fi

# Extract tarball
u_print "Extracting tarball..."

tar -zxf /tmp/0.7.2.tar.gz
rm  /tmp/0.7.2.tar.gz

u_pass

# Run installation scripts
cd /tmp/deadbeef-0.7.2

u_print "Running ./autogen.sh..."
log_output ./autogen.sh
check_success

u_print "Running ./configure..."
log_output ./configure
check_success

u_print "Running make..."
log_output "make"
check_success

u_print "Running make install..."
log_output sudo make install
check_success

u_exit_subheader
