#!/usr/bin/env bash

u_subheader "qbittorrent"

if cmd_exists qbittorrent; then
    u_print "qBittorrent is already installed..."
    u_skip
    return
fi

if [[ ! $INSTALL_DEFAULTS ]]; then
    seek_confirmation "Install qBittorrent?"
else
    set_confirmed
fi

if ! is_confirmed; then
    u_print "Installing qbittorrent..."
    u_skip
    return
fi

package_install qbittorrent

u_exit_subheader
